spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27018,127.0.0.1:27019,127.0.0.1:27020/
      database: respondnow
      core:
        MongoTemplate: DEBUG
  server:
    port: 8080
jwt:
  secret: mySecretKeyUsedToEncodeJWTForAuthenticationPurpose
  expiration: 86400000  # Token expiration time in milliseconds (e.g., 1 hour)
slack:
  botToken: xoxb-308118791127-8313951448102-jGjqKmbZ4mrT0HrbgSwGs0XG
  appToken: xapp-1-A08A3AMAVFS-8306018852311-033eccdb039b32927fc6cdae6c7d8d76f28cc982086a7e88fc27967683c53889
  signingSecret: 7d3a4befb2b60e2b8e6f37eef15a7f66
  incidentChannelID: C089H2Q0BPE
hierarchy:
  defaultAccount:
    id: default_account_id
    name: "Default Account"
  defaultOrg:
    id: default_org_id
    name: "Default Org"
  defaultProject:
    id: default_project_id
    name: "Default Project"
