apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- toYaml .Values.server.labels | nindent 4 }}
data:
{{- range $key, $value := .Values.server.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
