apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portal.name }}
  labels: {{- toYaml .Values.portal.labels | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.portal.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.portal.labels.app }}
  template:
    metadata:
      labels: {{- toYaml .Values.portal.labels | nindent 8 }}
      annotations:
        {{- toYaml .Values.portal.annotations | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.portal.name }}
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.portal.resources | nindent 12 }}
