/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { IncidentCreateResponseDto } from '../schemas/IncidentCreateResponseDto';
import type { UtilsDefaultResponseDto } from '../schemas/UtilsDefaultResponseDto';
import type { IncidentCreateRequest } from '../schemas/IncidentCreateRequest';
import { fetcher, FetcherOptions } from '@services/fetcher';

export interface CreateIncidentMutationQueryParams {
  accountIdentifier: string;
  orgIdentifier?: string;
  projectIdentifier?: string;
  correlationId?: string;
}

export type CreateIncidentRequestBody = IncidentCreateRequest;

export type CreateIncidentOkResponse = IncidentCreateResponseDto;

export type CreateIncidentErrorResponse = UtilsDefaultResponseDto;

export interface CreateIncidentProps
  extends Omit<FetcherOptions<CreateIncidentMutationQueryParams, CreateIncidentRequestBody>, 'url'> {
  queryParams: CreateIncidentMutationQueryParams;
  body: CreateIncidentRequestBody;
}

export function createIncident(props: CreateIncidentProps): Promise<CreateIncidentOkResponse> {
  return fetcher<CreateIncidentOkResponse, CreateIncidentMutationQueryParams, CreateIncidentRequestBody>({
    url: `/auth/incident/create`,
    method: 'POST',
    ...props
  });
}

export type CreateIncidentMutationProps<T extends keyof CreateIncidentProps> = Omit<CreateIncidentProps, T> &
  Partial<Pick<CreateIncidentProps, T>>;

/**
 * Create an incident
 */
export function useCreateIncidentMutation<T extends keyof CreateIncidentProps>(
  props: Pick<Partial<CreateIncidentProps>, T>,
  options?: Omit<
    UseMutationOptions<CreateIncidentOkResponse, CreateIncidentErrorResponse, CreateIncidentMutationProps<T>>,
    'mutationKey' | 'mutationFn'
  >
) {
  return useMutation<CreateIncidentOkResponse, CreateIncidentErrorResponse, CreateIncidentMutationProps<T>>(
    (mutateProps: CreateIncidentMutationProps<T>) =>
      createIncident({ ...props, ...mutateProps } as CreateIncidentProps),
    options
  );
}
