/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query';

import type { LoginResponseDto } from '../schemas/LoginResponseDto';
import type { LoginUserInput } from '../schemas/LoginUserInput';
import { fetcher, FetcherOptions } from '@services/fetcher';

export type LoginRequestBody = LoginUserInput;

export type LoginOkResponse = LoginResponseDto;

export type LoginErrorResponse = LoginResponseDto;

export interface LoginProps extends Omit<FetcherOptions<unknown, LoginRequestBody>, 'url'> {
  body: LoginRequestBody;
}

export function login(props: LoginProps): Promise<LoginOkResponse> {
  return fetcher<LoginOkResponse, unknown, LoginRequestBody>({
    url: `/api/auth/login`,
    method: 'POST',
    ...props
  });
}

export type LoginMutationProps<T extends keyof LoginProps> = Omit<LoginProps, T> & Partial<Pick<LoginProps, T>>;

/**
 * User login
 */
export function useLoginMutation<T extends keyof LoginProps>(
  props: Pick<Partial<LoginProps>, T>,
  options?: Omit<
    UseMutationOptions<LoginOkResponse, LoginErrorResponse, LoginMutationProps<T>>,
    'mutationKey' | 'mutationFn'
  >
) {
  return useMutation<LoginOkResponse, LoginErrorResponse, LoginMutationProps<T>>(
    (mutateProps: LoginMutationProps<T>) => login({ ...props, ...mutateProps } as LoginProps),
    options
  );
}
