// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.harness.io/legal/subscription-terms",
        "contact": {
            "name": "RespondNow"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/changePassword": {
            "post": {
                "description": "ChangePassword of RespondNow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ChangePassword of RespondNow",
                "operationId": "ChangePassword",
                "parameters": [
                    {
                        "description": "ChangePassword of RespondNow",
                        "name": "\"changePassword\"",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ChangeUserPasswordInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "correlationId",
                        "name": "correlationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ChangePasswordResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login to RespondNow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login to RespondNow",
                "operationId": "Login",
                "parameters": [
                    {
                        "description": "Login to RespondNow",
                        "name": "\"login\"",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginUserInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "correlationId",
                        "name": "correlationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Signup to RespondNow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Signup to RespondNow",
                "operationId": "SignUp",
                "parameters": [
                    {
                        "description": "Signup to RespondNow",
                        "name": "\"signup\"",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AddUserInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "correlationId",
                        "name": "correlationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SignupResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/incident/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create an incident",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Incident"
                ],
                "summary": "Create an incident",
                "operationId": "CreateIncident",
                "parameters": [
                    {
                        "description": "Create an incident",
                        "name": "incident\"",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/incident.CreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "accountIdentifier",
                        "name": "accountIdentifier",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "orgIdentifier",
                        "name": "orgIdentifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "projectIdentifier",
                        "name": "projectIdentifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "correlationId",
                        "name": "correlationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/incident.CreateResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/incident/list": {
            "get": {
                "description": "List incidents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Incident Management"
                ],
                "summary": "List incidents",
                "operationId": "ListIncidents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "accountIdentifier",
                        "name": "accountIdentifier",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "orgIdentifier",
                        "name": "orgIdentifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "projectIdentifier",
                        "name": "projectIdentifier",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "availability",
                            "latency",
                            "security",
                            "other"
                        ],
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "SEV1",
                            "SEV2",
                            "SEV3",
                            "SEV4"
                        ],
                        "type": "string",
                        "description": "severity",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "started",
                            "detected",
                            "acknowledged",
                            "identified",
                            "mitigated",
                            "investigating",
                            "postmortemStarted",
                            "PostmortemCompleted",
                            "resolved"
                        ],
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "active",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "slack"
                        ],
                        "type": "string",
                        "description": "incidentChannelType",
                        "name": "incidentChannelType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "correlationId",
                        "name": "correlationId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "all",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/incident.ListResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Status of RespondNow Server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Status of RespondNow Server",
                "operationId": "Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIStatus"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Version of RespondNow Server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Miscellaneous"
                ],
                "summary": "Version of RespondNow Server",
                "operationId": "Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/version.Version"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DefaultResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Pagination": {
            "type": "object",
            "properties": {
                "all": {
                    "type": "boolean"
                },
                "index": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "auth.AddUserInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "userId"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "auth.ChangePasswordResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/auth.LoginResponse"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "auth.ChangeUserPasswordInput": {
            "type": "object",
            "required": [
                "email",
                "newPassword",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "changeUserPassword": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/auth.LoginResponse"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "auth.LoginUserInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.SignupResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.APIStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "incident.AddConference": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/incident.ConferenceType"
                }
            }
        },
        "incident.Attachment": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/incident.AttachmentType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "incident.AttachmentType": {
            "type": "string",
            "enum": [
                "link"
            ],
            "x-enum-varnames": [
                "Link"
            ]
        },
        "incident.Channel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/incident.ChannelSource"
                },
                "status": {
                    "$ref": "#/definitions/incident.ChannelStatus"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "incident.ChannelSource": {
            "type": "string",
            "enum": [
                "slack"
            ],
            "x-enum-varnames": [
                "SlackSource"
            ]
        },
        "incident.ChannelStatus": {
            "type": "string",
            "enum": [
                "operational"
            ],
            "x-enum-varnames": [
                "Operational"
            ]
        },
        "incident.Conference": {
            "type": "object",
            "properties": {
                "conferenceId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/incident.ConferenceType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "incident.ConferenceType": {
            "type": "string",
            "enum": [
                "zoom"
            ],
            "x-enum-varnames": [
                "Zoom"
            ]
        },
        "incident.CreateRequest": {
            "type": "object",
            "required": [
                "identifier",
                "incidentChannel",
                "name",
                "severity",
                "summary",
                "type"
            ],
            "properties": {
                "addConference": {
                    "$ref": "#/definitions/incident.AddConference"
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Attachment"
                    }
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Channel"
                    }
                },
                "description": {
                    "type": "string"
                },
                "environments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Environment"
                    }
                },
                "functionalities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Functionality"
                    }
                },
                "identifier": {
                    "type": "string"
                },
                "incidentChannel": {
                    "$ref": "#/definitions/incident.IncidentChannel"
                },
                "name": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Service"
                    }
                },
                "severity": {
                    "$ref": "#/definitions/incident.Severity"
                },
                "status": {
                    "$ref": "#/definitions/incident.Status"
                },
                "summary": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/incident.Type"
                }
            }
        },
        "incident.CreateResponse": {
            "type": "object",
            "required": [
                "active",
                "id",
                "identifier",
                "name",
                "severity",
                "status",
                "summary"
            ],
            "properties": {
                "accountIdentifier": {
                    "type": "string"
                },
                "active": {
                    "type": "boolean"
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Attachment"
                    }
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Channel"
                    }
                },
                "conferenceDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Conference"
                    }
                },
                "correlationID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "$ref": "#/definitions/utils.UserDetails"
                },
                "description": {
                    "type": "string"
                },
                "environments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Environment"
                    }
                },
                "functionalities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Functionality"
                    }
                },
                "id": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "incidentChannel": {
                    "$ref": "#/definitions/incident.IncidentChannel"
                },
                "name": {
                    "type": "string"
                },
                "orgIdentifier": {
                    "type": "string"
                },
                "projectIdentifier": {
                    "type": "string"
                },
                "removed": {
                    "type": "boolean"
                },
                "removedAt": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Role"
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Service"
                    }
                },
                "severity": {
                    "$ref": "#/definitions/incident.Severity"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Stage"
                    }
                },
                "status": {
                    "$ref": "#/definitions/incident.Status"
                },
                "summary": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/incident.Type"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "$ref": "#/definitions/utils.UserDetails"
                }
            }
        },
        "incident.CreateResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/incident.CreateResponse"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "incident.Environment": {
            "type": "object",
            "properties": {
                "environmentId": {
                    "type": "string"
                },
                "environmentName": {
                    "type": "string"
                }
            }
        },
        "incident.Functionality": {
            "type": "object",
            "properties": {
                "functionalityId": {
                    "type": "string"
                },
                "functionalityName": {
                    "type": "string"
                }
            }
        },
        "incident.Incident": {
            "type": "object",
            "required": [
                "active",
                "id",
                "identifier",
                "name",
                "severity",
                "status",
                "summary"
            ],
            "properties": {
                "accountIdentifier": {
                    "type": "string"
                },
                "active": {
                    "type": "boolean"
                },
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Attachment"
                    }
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Channel"
                    }
                },
                "conferenceDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Conference"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "$ref": "#/definitions/utils.UserDetails"
                },
                "description": {
                    "type": "string"
                },
                "environments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Environment"
                    }
                },
                "functionalities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Functionality"
                    }
                },
                "id": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "incidentChannel": {
                    "$ref": "#/definitions/incident.IncidentChannel"
                },
                "name": {
                    "type": "string"
                },
                "orgIdentifier": {
                    "type": "string"
                },
                "projectIdentifier": {
                    "type": "string"
                },
                "removed": {
                    "type": "boolean"
                },
                "removedAt": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Role"
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Service"
                    }
                },
                "severity": {
                    "$ref": "#/definitions/incident.Severity"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Stage"
                    }
                },
                "status": {
                    "$ref": "#/definitions/incident.Status"
                },
                "summary": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/incident.Type"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "$ref": "#/definitions/utils.UserDetails"
                }
            }
        },
        "incident.IncidentChannel": {
            "type": "object",
            "properties": {
                "slack": {
                    "$ref": "#/definitions/incident.Slack"
                },
                "type": {
                    "$ref": "#/definitions/incident.IncidentChannelType"
                }
            }
        },
        "incident.IncidentChannelType": {
            "type": "string",
            "enum": [
                "slack"
            ],
            "x-enum-varnames": [
                "ChannelSlack"
            ]
        },
        "incident.ListResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/incident.Incident"
                    }
                },
                "correlationID": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "incident.ListResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/incident.ListResponse"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "incident.Role": {
            "type": "object",
            "properties": {
                "roleType": {
                    "$ref": "#/definitions/incident.RoleType"
                },
                "userDetails": {
                    "$ref": "#/definitions/utils.UserDetails"
                }
            }
        },
        "incident.RoleType": {
            "type": "string",
            "enum": [
                "incidentCommander",
                "communicationsLiaison"
            ],
            "x-enum-varnames": [
                "IncidentCommander",
                "CommunicationsLiaison"
            ]
        },
        "incident.Service": {
            "type": "object",
            "properties": {
                "serviceId": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "incident.Severity": {
            "type": "string",
            "enum": [
                "SEV1",
                "SEV2",
                "SEV3",
                "SEV4"
            ],
            "x-enum-varnames": [
                "Severity1",
                "Severity2",
                "Severity3",
                "Severity4"
            ]
        },
        "incident.Slack": {
            "type": "object",
            "properties": {
                "channelDescription": {
                    "type": "string"
                },
                "channelId": {
                    "type": "string"
                },
                "channelName": {
                    "type": "string"
                },
                "channelReference": {
                    "type": "string"
                },
                "channelStatus": {
                    "$ref": "#/definitions/incident.ChannelStatus"
                }
            }
        },
        "incident.Stage": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "stageId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/incident.Status"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userDetails": {
                    "$ref": "#/definitions/utils.UserDetails"
                }
            }
        },
        "incident.Status": {
            "type": "string",
            "enum": [
                "started",
                "detected",
                "acknowledged",
                "identified",
                "mitigated",
                "investigating",
                "postmortemStarted",
                "PostmortemCompleted",
                "resolved"
            ],
            "x-enum-varnames": [
                "Started",
                "Detected",
                "Acknowledged",
                "Identified",
                "Mitigated",
                "Investigating",
                "PostmortemStarted",
                "PostmortemCompleted",
                "Resolved"
            ]
        },
        "incident.Type": {
            "type": "string",
            "enum": [
                "availability",
                "latency",
                "security",
                "other"
            ],
            "x-enum-varnames": [
                "Availability",
                "Latency",
                "Security",
                "Other"
            ]
        },
        "utils.DefaultResponseDTO": {
            "type": "object",
            "properties": {
                "correlationId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "utils.Source": {
            "type": "string",
            "enum": [
                "slack"
            ],
            "x-enum-varnames": [
                "Slack"
            ]
        },
        "utils.UserDetails": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/utils.Source"
                },
                "userId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "version.Metadata": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "version.Resource": {
            "type": "object",
            "properties": {
                "versionInfo": {
                    "$ref": "#/definitions/version.VersionInfo"
                }
            }
        },
        "version.Version": {
            "type": "object",
            "properties": {
                "metaData": {
                    "$ref": "#/definitions/version.Metadata"
                },
                "resource": {
                    "$ref": "#/definitions/version.Resource"
                },
                "responseMessages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "version.VersionInfo": {
            "type": "object",
            "properties": {
                "buildNo": {
                    "type": "string"
                },
                "gitBranch": {
                    "type": "string"
                },
                "gitCommit": {
                    "type": "string"
                },
                "patch": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "RespondNow Server",
	Description:      "RespondNow Server APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
