/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ApiPagination {
  all?: boolean;
  index?: number;
  limit?: number;
  totalItems?: number;
  totalPages?: number;
}
