/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { AuthLoginResponse } from '../schemas/AuthLoginResponse';

export interface AuthLoginResponseDto {
  correlationId?: string;
  data?: AuthLoginResponse;
  message?: string;
  status?: string;
}
