/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { AuthChangePasswordResponse } from '../schemas/AuthChangePasswordResponse';

export interface AuthChangePasswordResponseDto {
  correlationId?: string;
  data?: AuthChangePasswordResponse;
  message?: string;
  status?: string;
}
