/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface Channel {
  id?: string;
  name?: string;
  source?: 'Slack';
  status?: 'Operational';
  teamId?: string;
  url?: string;
}
