/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ChangePasswordResponseData } from '../schemas/ChangePasswordResponseData';

export interface ChangePasswordResponseDto {
  data?: ChangePasswordResponseData;
  /**
   * Message with additional information about the login
   */
  message?: string;
  /**
   * Status of the login response
   * @example "success"
   */
  status?: string;
}
