/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * Change password data object
 */

export interface ChangePasswordResponseData {
  /**
   * Timestamp of the user's last login
   * @format int64
   * @example 1630421333000
   */
  lastLoginAt?: number;
  /**
   * JWT token for the user
   */
  token?: string;
}
