/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { Incident } from '../schemas/Incident';

export interface GetResponseDto {
  correlationId?: string;
  data?: Incident;
  message?: string;
  status?: string;
}
