/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserMappingData } from '../schemas/UserMappingData';

export interface GetUserMappingResponseDto {
  correlationId?: string;
  data?: UserMappingData;
  message?: string;
  status?: string;
}
