/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentCreateResponse } from '../schemas/IncidentCreateResponse';

export interface IncidentCreateResponseDto {
  correlationId?: string;
  data?: IncidentCreateResponse;
  message?: string;
  status?: string;
}
