/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentIncident } from '../schemas/IncidentIncident';
import type { ApiPagination } from '../schemas/ApiPagination';

export interface IncidentListResponse {
  content?: IncidentIncident[];
  correlationID?: string;
  pagination?: ApiPagination;
}
