/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentChannelStatus } from '../schemas/IncidentChannelStatus';

export interface IncidentSlack {
  channelDescription?: string;
  channelId?: string;
  channelName?: string;
  channelReference?: string;
  channelStatus?: IncidentChannelStatus;
  teamDomain?: string;
  teamId?: string;
  teamName?: string;
}
