/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentSlack } from '../schemas/IncidentSlack';
import type { IncidentIncidentChannelType } from '../schemas/IncidentIncidentChannelType';

export interface IncidentIncidentChannel {
  slack?: IncidentSlack;
  type?: IncidentIncidentChannelType;
}
