/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentSlack } from '../schemas/IncidentSlack';
import type { IncidentChangeType } from '../schemas/IncidentChangeType';
import type { UtilsUserDetails } from '../schemas/UtilsUserDetails';

export interface IncidentTimeline {
  createdAt?: number;
  currentState?: string;
  id?: string;
  message?: string;
  previousState?: string;
  slack?: IncidentSlack;
  type?: IncidentChangeType;
  updatedAt?: number;
  userDetails?: UtilsUserDetails;
}
