/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentIncident } from '../schemas/IncidentIncident';

export interface IncidentGetResponseDto {
  correlationId?: string;
  data?: IncidentIncident;
  message?: string;
  status?: string;
}
