/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentConferenceType } from '../schemas/IncidentConferenceType';

export interface IncidentConference {
  conferenceId?: string;
  type?: IncidentConferenceType;
  url?: string;
}
