/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentRoleType } from '../schemas/IncidentRoleType';
import type { UtilsUserDetails } from '../schemas/UtilsUserDetails';

export interface IncidentRole {
  roleType?: IncidentRoleType;
  userDetails?: UtilsUserDetails;
}
