/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentAttachmentType } from '../schemas/IncidentAttachmentType';

export interface IncidentAttachment {
  description?: string;
  type?: IncidentAttachmentType;
  url?: string;
}
