/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentChannelSource } from '../schemas/IncidentChannelSource';
import type { IncidentChannelStatus } from '../schemas/IncidentChannelStatus';

export interface IncidentChannel {
  id?: string;
  name?: string;
  source?: IncidentChannelSource;
  status?: IncidentChannelStatus;
  url?: string;
}
