/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { Attachment } from '../schemas/Attachment';
import type { Channel } from '../schemas/Channel';
import type { Conference } from '../schemas/Conference';
import type { UserDetails } from '../schemas/UserDetails';
import type { Environment } from '../schemas/Environment';
import type { Functionality } from '../schemas/Functionality';
import type { IncidentChannel } from '../schemas/IncidentChannel';
import type { Role } from '../schemas/Role';
import type { Service } from '../schemas/Service';
import type { Stage } from '../schemas/Stage';
import type { Timeline } from '../schemas/Timeline';

export interface Incident {
  accountIdentifier?: string;
  active: boolean;
  attachments?: Attachment[];
  channels?: Channel[];
  comment: string;
  conferenceDetails?: Conference[];
  /**
   * @format int64
   */
  createdAt?: number;
  createdBy?: UserDetails;
  description?: string;
  environments?: Environment[];
  functionalities?: Functionality[];
  id?: string;
  identifier?: string;
  incidentChannel?: IncidentChannel;
  name?: string;
  orgIdentifier?: string;
  projectIdentifier?: string;
  removed?: boolean;
  /**
   * @format int64
   */
  removedAt?: number;
  roles?: Role[];
  services?: Service[];
  severity: 'SEV0' | 'SEV1' | 'SEV2';
  stages?: Stage[];
  status: 'Acknowledged' | 'Identified' | 'Investigating' | 'Mitigated' | 'Resolved' | 'Started';
  summary: string;
  tags?: string[];
  timelines?: Timeline[];
  type?: 'Availability' | 'Latency' | 'Other' | 'Security';
  /**
   * @format int64
   */
  updatedAt?: number;
  updatedBy?: UserDetails;
}
