/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export type IncidentRoleType = 'Communications Lead' | 'Incident Commander';
