/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export type IncidentStatus = 'Acknowledged' | 'Identified' | 'Investigating' | 'Mitigated' | 'Resolved' | 'Started';
