/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export type IncidentSeverity =
  | 'SEV0 - Critical, High Impact'
  | 'SEV1 - Major, Significant Impact'
  | 'SEV2 - Minor, Low Impact';
