/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentChangeType } from '../schemas/IncidentChangeType';
import type { UtilsUserDetails } from '../schemas/UtilsUserDetails';

export interface IncidentTimeline {
  change?: {};
  createdAt?: number;
  id?: string;
  type?: IncidentChangeType;
  updatedAt?: number;
  userDetails?: UtilsUserDetails;
}
