/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentAddConference } from '../schemas/IncidentAddConference';
import type { IncidentAttachment } from '../schemas/IncidentAttachment';
import type { IncidentChannel } from '../schemas/IncidentChannel';
import type { IncidentEnvironment } from '../schemas/IncidentEnvironment';
import type { IncidentFunctionality } from '../schemas/IncidentFunctionality';
import type { IncidentIncidentChannel } from '../schemas/IncidentIncidentChannel';
import type { IncidentRole } from '../schemas/IncidentRole';
import type { IncidentService } from '../schemas/IncidentService';
import type { IncidentSeverity } from '../schemas/IncidentSeverity';
import type { IncidentStatus } from '../schemas/IncidentStatus';
import type { IncidentType } from '../schemas/IncidentType';

export interface IncidentCreateRequest {
  addConference?: IncidentAddConference;
  attachments?: IncidentAttachment[];
  channels?: IncidentChannel[];
  description?: string;
  environments?: IncidentEnvironment[];
  functionalities?: IncidentFunctionality[];
  identifier: string;
  incidentChannel: IncidentIncidentChannel;
  name: string;
  roles?: IncidentRole[];
  services?: IncidentService[];
  severity: IncidentSeverity;
  status?: IncidentStatus;
  summary: string;
  tags?: string[];
  type: IncidentType;
}
