/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { IncidentListResponse } from '../schemas/IncidentListResponse';

export interface IncidentListResponseDto {
  correlationId?: string;
  data?: IncidentListResponse;
  message?: string;
  status?: string;
}
