/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ListResponse } from '../schemas/ListResponse';

export interface ListResponseDto {
  correlationId?: string;
  data?: ListResponse;
  message?: string;
}
