/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { LoginResponseData } from '../schemas/LoginResponseData';

export interface LoginResponseDto {
  data?: LoginResponseData;
  /**
   * Message with additional information about the login
   */
  message?: string;
  /**
   * Status of the login response
   * @example "success"
   */
  status?: string;
}
