/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface Pagination {
  all?: boolean;
  /**
   * @format int64
   */
  index?: number;
  /**
   * @format int64
   */
  limit?: number;
  /**
   * @format int64
   */
  totalItems?: number;
  /**
   * @format int64
   */
  totalPages?: number;
}
