/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserDetails } from '../schemas/UserDetails';

export interface Role {
  roleType?: 'Communications_Lead' | 'Incident_Commander';
  userDetails?: UserDetails;
}
