/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface Slack {
  channelDescription?: string;
  channelId?: string;
  channelName?: string;
  channelReference?: string;
  channelStatus?: 'Operational';
  teamDomain?: string;
  teamId?: string;
  teamName?: string;
}
