/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserDetails } from '../schemas/UserDetails';

export interface Stage {
  /**
   * @format int64
   */
  createdAt?: number;
  /**
   * @format int64
   */
  duration?: number;
  stageId?: string;
  type?: 'Acknowledged' | 'Identified' | 'Investigating' | 'Mitigated' | 'Resolved' | 'Started';
  /**
   * @format int64
   */
  updatedAt?: number;
  userDetails?: UserDetails;
}
