/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserIdentifiers } from '../schemas/UserIdentifiers';

export interface UserMappingData {
  defaultMapping?: UserIdentifiers;
  mappings?: UserIdentifiers[];
}
