/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface UserDetails {
  email?: string;
  name?: string;
  source?: 'Slack';
  userId?: string;
  userName?: string;
}
