/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface UserLoginResponse {
  changeUserPassword?: boolean;
  lastLoginAt?: number;
  token?: string;
}
