/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserUserMapping } from '../schemas/UserUserMapping';

export interface UserGetUserMappingResponseDto {
  correlationId?: string;
  data?: UserUserMapping;
  message?: string;
  status?: string;
}
