/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface UserAddUserInput {
  email: string;
  name: string;
  password: string;
  userId: string;
}
