/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface UserIdentifiers {
  accountIdentifier?: string;
  accountName?: string;
  orgIdentifier?: string;
  orgName?: string;
  projectIdentifier?: string;
  projectName?: string;
}
