/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserLoginResponse } from '../schemas/UserLoginResponse';

export interface UserLoginResponseDto {
  correlationId?: string;
  data?: UserLoginResponse;
  message?: string;
  status?: string;
}
