/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UserChangePasswordResponse } from '../schemas/UserChangePasswordResponse';

export interface UserChangePasswordResponseDto {
  correlationId?: string;
  data?: UserChangePasswordResponse;
  message?: string;
  status?: string;
}
