/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { UtilsSource } from '../schemas/UtilsSource';

export interface UtilsUserDetails {
  email?: string;
  name?: string;
  source?: UtilsSource;
  userId?: string;
  userName?: string;
}
