name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - pipeline-test
      - release/*

env:
  REGISTRY: docker.io
  IMAGE_NAME: respondnow-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5' # Adjust the Go version as necessary

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: imrajdas
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          cd server
          ls
          docker build -t ${{ env.REGISTRY }}/imrajdas/${{ env.IMAGE_NAME }}:latest -f package/Dockerfile .
          
      - name: Tag the Docker image
        run: docker tag ${{ env.REGISTRY }}/imrajdas/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/imrajdas/${{ env.IMAGE_NAME }}:main-latest
          # if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          #   docker tag ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:stable
          # elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
          #   release_version=$(echo "${{ github.ref }}" | sed 's|refs/heads/release/||')
          #   docker tag ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:${release_version}
          # fi

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/imrajdas/${{ env.IMAGE_NAME }}:main-latest
          # docker push ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:latest
          # if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          #   docker push ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:stable
          # elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
          #   release_version=$(echo "${{ github.ref }}" | sed 's|refs/heads/release/||')
          #   docker push ${{ env.REGISTRY }}/rajchaosnative/${{ env.IMAGE_NAME }}:${release_version}
          # fi
