name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - pipeline-test
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/respond-portal:latest -f respond/portal/Dockerfile .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/respond-portal:latest

    - name: Post success message
      run: echo "Docker image successfully built and pushed to GitHub Container Registry"
