site_name: RespondNow™
site_url: https://respondnow.github.io/respondnow
site_description: Documentation for RespondNow
repo_name: respondnow/respondnow
repo_url: https://github.com/respondnow/respondnow
theme:
  name: material
  favicon: images/logo.svg
  custom_dir: overrides
  font:
    text: Work Sans
  highlightjs: true
  logo: images/logo.svg
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  hljs_languages:
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
extra:
  version:
    provider: mike
markdown_extensions:
  - codehilite
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html

nav:
  - Introduction: index.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Create Slack App: getting-started/create-slack-app-with-app-manifest.md
      - Deploy RespondNow Server: getting-started/deploy-rn-server-with-helm.md
      - Verify RespondNow Portal: getting-started/verify-rn-portal.md
  - User Guide:
      - Slack-Based Incident Lifecycle Management:
          - Create Incidents: user-guide/slack-based-incident-management/create-incidents.md
          - List Incidents: user-guide/slack-based-incident-management/list-incidents.md
          - View Incident Details: user-guide/slack-based-incident-management/view-incident-details.md
          - Update Incidents: user-guide/slack-based-incident-management/update-incidents.md
      - Navigate the RespondNow Portal:
          - View Incident Details: user-guide/navigate-the-respondnow-portal/view-incident-details.md
  - Release Notes: release-notes/release-notes-tracker.md
